import React from "react";
import Head from "next/head";
import Header from "../common/Header/Header";
import Footer from "../common/Footer/Footer";
import { SectionProvider } from "../utils/SectionContext";

const Layout = (props: any) => {
  return (
    <>
      <Head>
        <title>Sellucas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SectionProvider>
        <main style={{ background: "#5700B6" }}>{props.children}</main>
      </SectionProvider>
      <Footer />
    </>
  );
};

export default Layout;
